### ISSUE TITLE
Please remove addPath and exportVariable calls due to a security vulnerability 

### ISSUE THREAD

**Issue by andxu** [AArnott/cloudbuild-task#41]
See details at:
https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w

**Comment by AArnott** [comment]
Fixed in #34. Just not shipped to npmjs.org. I'll fix that.

**Comment by AArnott** [comment]
0.1.105-beta published to npmjs.org. Thanks for the reminder. :)
