### ISSUE TITLE
add support for core.exportVariable of GitHub actions

### ISSUE THREAD

**Issue by lukka** [AArnott/cloudbuild-task#8]
This is about adding support for GitHub action `core.ExportVariable` function.
In my [implementation](https://github.com/lukka/run-cmake-vcpkg-action-libs/blob/master/action-base-lib/src/action-lib.ts#L202) of the task abstraction layer I implemented:

| abstract action  | GH Actions | ADO Tasks|
| ------------- | ------------- |-|
| setOutput  | setOutput  |setVariable()|
| setVariable  | exportVariable()  |setVariable()|

Would make sense to do something similar in this repo by adding Tools.setEnvVar() ?

**Comment by AArnott** [comment]
Oh, that's an important distinction you call out between outputs and variables. Thanks for calling my attention to that. I'll fix this up and make sure we have entrypoints for GH `setOutput` and `exportVariable`.
